openapi: 3.0.0
info:
  title: Organizze API
  description: >-
    Specification for the Organizze API described in
    [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
  version: 1.0.0
externalDocs:
  url: https://github.com/organizze/api-doc
  description: Official Organizze Docs
servers:
  - url: https://api.organizze.com.br/rest/v2
    description: Organizze API
security:
  - basicAuth: []
tags:
  - name: Bank Accounts
  - name: Categories
  - name: Users
  - name: Credit Cards
  - name: Budgets
  - name: Transactions
paths:
  /accounts:
    get:
      tags:
        - Bank Accounts
      summary: List Bank Accounts
      operationId: listBankAccounts
      responses:
        "200":
          $ref: "#/components/responses/ListBankAccountsResponse"
        "404":
          $ref: "#/components/responses/ItemNotFound"
        "401":
          $ref: "#/components/responses/Unauthorized"
        default:
          $ref: "#/components/responses/Unauthorized"
  /accounts/{bankAccountID}:
    get:
      tags:
        - Bank Accounts
      summary: Read Account
      operationId: readBankAccount
      parameters:
        - $ref: "#/components/parameters/BankAccountID"
      responses:
        "200":
          $ref: "#/components/responses/ReadBankAccountResponse"
        "404":
          $ref: "#/components/responses/ItemNotFound"
        "401":
          $ref: "#/components/responses/Unauthorized"
        default:
          $ref: "#/components/responses/Unauthorized"
  /categories:
    get:
      tags:
        - Categories
      summary: List Categories
      operationId: listCategories
      responses:
        "200":
          $ref: "#/components/responses/ListCategoriesResponse"
        "404":
          $ref: "#/components/responses/ItemNotFound"
        "401":
          $ref: "#/components/responses/Unauthorized"
        default:
          $ref: "#/components/responses/Unauthorized"
  /categories/{categoryID}:
    get:
      tags:
        - Categories
      summary: Read Category
      operationId: readCategory
      parameters:
        - $ref: "#/components/parameters/CategoryID"
      responses:
        "200":
          $ref: "#/components/responses/ReadCategoryResponse"
        "404":
          $ref: "#/components/responses/ItemNotFound"
        "401":
          $ref: "#/components/responses/Unauthorized"
        default:
          $ref: "#/components/responses/Unauthorized"
  /users:
    get:
      tags:
        - Users
      summary: List Users
      operationId: listUsers
      responses:
        "200":
          $ref: "#/components/responses/ListUsersResponse"
        "404":
          $ref: "#/components/responses/ItemNotFound"
        "401":
          $ref: "#/components/responses/Unauthorized"
        default:
          $ref: "#/components/responses/Unauthorized"
  /users/{userID}:
    get:
      tags:
        - Users
      summary: Read User
      operationId: readUser
      parameters:
        - $ref: "#/components/parameters/UserID"
      responses:
        "200":
          $ref: "#/components/responses/ReadUserResponse"
        "404":
          $ref: "#/components/responses/ItemNotFound"
        "401":
          $ref: "#/components/responses/Unauthorized"
        default:
          $ref: "#/components/responses/Unauthorized"
  /credit_cards:
    get:
      tags:
        - Credit Cards
      summary: List Credit Cards
      operationId: listCreditCards
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 1287765
                  name: Nubank
                  description: null
                  card_network: default
                  closing_day: 8
                  due_day: 15
                  limit_cents: 1965000
                  archived: false
                  default: false
                  institution_id: default
                  institution_name: null
                  created_at: "2023-04-07T11:36:48-03:00"
                  updated_at: "2023-04-07T13:12:06-03:00"
                  type: credit_card
                - id: 1287806
                  name: SBanken Credit
                  description: null
                  card_network: default
                  closing_day: 31
                  due_day: 20
                  limit_cents: 10000000
                  archived: false
                  default: false
                  institution_id: visa
                  institution_name: null
                  created_at: "2023-04-07T13:03:50-03:00"
                  updated_at: "2023-04-07T13:03:50-03:00"
                  type: credit_card
  /credit_cards/{creditCardId}:
    get:
      tags:
        - Credit Cards
      summary: Read Credit Card
      operationId: readCreditCard
      parameters:
        - name: creditCardId
          in: path
          schema:
            type: integer
          required: true
          example: "1287765"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                id: 1287765
                name: Nubank
                description: null
                card_network: default
                closing_day: 8
                due_day: 15
                limit_cents: 1965000
                archived: false
                default: false
                institution_id: default
                institution_name: null
                created_at: "2023-04-07T11:36:48-03:00"
                updated_at: "2023-04-07T13:12:06-03:00"
                type: credit_card
  /credit_cards/{creditCardId}/invoices:
    get:
      tags:
        - Credit Cards
      summary: List Credit Card Invoices
      operationId: listCreditCardInvoices
      parameters:
        - name: creditCardId
          in: path
          schema:
            type: integer
          required: true
          example: "1287765"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 276
                  date: "2023-01-15"
                  starting_date: "2022-12-09"
                  closing_date: "2023-01-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 277
                  date: "2023-02-15"
                  starting_date: "2023-01-09"
                  closing_date: "2023-02-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 278
                  date: "2023-03-15"
                  starting_date: "2023-02-09"
                  closing_date: "2023-03-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 279
                  date: "2023-04-15"
                  starting_date: "2023-03-09"
                  closing_date: "2023-04-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 280
                  date: "2023-05-15"
                  starting_date: "2023-04-09"
                  closing_date: "2023-05-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 281
                  date: "2023-06-15"
                  starting_date: "2023-05-09"
                  closing_date: "2023-06-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 282
                  date: "2023-07-15"
                  starting_date: "2023-06-09"
                  closing_date: "2023-07-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 283
                  date: "2023-08-15"
                  starting_date: "2023-07-09"
                  closing_date: "2023-08-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 284
                  date: "2023-09-15"
                  starting_date: "2023-08-09"
                  closing_date: "2023-09-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 285
                  date: "2023-10-15"
                  starting_date: "2023-09-09"
                  closing_date: "2023-10-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 286
                  date: "2023-11-15"
                  starting_date: "2023-10-09"
                  closing_date: "2023-11-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
                - id: 287
                  date: "2023-12-15"
                  starting_date: "2023-11-09"
                  closing_date: "2023-12-08"
                  amount_cents: 0
                  payment_amount_cents: 0
                  balance_cents: 0
                  previous_balance_cents: 0
                  credit_card_id: 1287765
  /credit_cards/{creditCardId}/invoices/{invoiceId}:
    get:
      tags:
        - Credit Cards
      summary: Read Credit Card Invoice
      operationId: readCreditCardInvoice
      parameters:
        - name: creditCardId
          in: path
          schema:
            type: integer
          required: true
          example: "1287765"
        - name: invoiceId
          in: path
          schema:
            type: integer
          required: true
          example: "276"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                id: 276
                date: "2023-01-15"
                starting_date: "2022-12-09"
                closing_date: "2023-01-08"
                amount_cents: 0
                payment_amount_cents: 0
                balance_cents: 0
                previous_balance_cents: 0
                credit_card_id: 1287765
                transactions: []
                payments: []
  /credit_cards/{creditCardId}/invoices/{invoiceId}/payments:
    get:
      tags:
        - Credit Cards
      summary: Read Credit Card Invoice Payments
      operationId: readCreditCardInvoicePayments
      parameters:
        - name: creditCardId
          in: path
          schema:
            type: integer
          required: true
          example: "1287765"
        - name: invoiceId
          in: path
          schema:
            type: integer
          required: true
          example: "276"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /budgets:
    get:
      tags:
        - Budgets
      summary: List All Budgets
      operationId: listAllBudgets
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
              example: []
  /transactions:
    get:
      tags:
        - Transactions
      summary: List Transactions
      operationId: listTransactions
      parameters:
        - name: start_date
          in: query
          schema:
            type: string
          description: ISO8601 Date with the start period for filtering
          example: "2015-09-01"
        - name: end_date
          in: query
          schema:
            type: string
          description: ISO8601 Date with the end period for filtering
          example: "2015-10-01"
        - name: account_id
          in: query
          schema:
            type: integer
          description: Account ID for filtering
          example: "6632818"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 2477483422
                  description: Despesa fixa
                  date: "2015-09-16"
                  paid: true
                  amount_cents: 0
                  total_installments: 1
                  installment: 1
                  recurring: false
                  account_id: 6632818
                  category_id: 120321159
                  notes: Pagamento via boleto
                  attachments_count: 0
                  credit_card_id: null
                  credit_card_invoice_id: null
                  paid_credit_card_id: null
                  paid_credit_card_invoice_id: null
                  oposite_transaction_id: null
                  oposite_account_id: null
                  created_at: "2023-04-08T12:32:16-03:00"
                  updated_at: "2023-04-08T12:32:16-03:00"
                  tags: []
                  attachments: []
                - id: 2477483178
                  description: Test
                  date: "2015-09-16"
                  paid: true
                  amount_cents: 0
                  total_installments: 1
                  installment: 1
                  recurring: false
                  account_id: 6632818
                  category_id: 120321159
                  notes: Test
                  attachments_count: 0
                  credit_card_id: null
                  credit_card_invoice_id: null
                  paid_credit_card_id: null
                  paid_credit_card_invoice_id: null
                  oposite_transaction_id: null
                  oposite_account_id: null
                  created_at: "2023-04-08T12:30:58-03:00"
                  updated_at: "2023-04-08T12:30:58-03:00"
                  tags: []
                  attachments: []
    post:
      tags:
        - Transactions
      summary: Create Transaction
      operationId: createTransaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                description: Computador
                notes: Pagamento via boleto
                date: "2015-09-16"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: Create Income Transaction
                  value:
                    id: 2477487022
                    description: Computador
                    date: "2015-09-16"
                    paid: true
                    amount_cents: 100000
                    total_installments: 1
                    installment: 1
                    recurring: false
                    account_id: 6632818
                    category_id: 120321160
                    notes: Pagamento via boleto
                    attachments_count: 0
                    credit_card_id: null
                    credit_card_invoice_id: null
                    paid_credit_card_id: null
                    paid_credit_card_invoice_id: null
                    oposite_transaction_id: null
                    oposite_account_id: null
                    created_at: "2023-04-08T12:42:17-03:00"
                    updated_at: "2023-04-08T12:42:17-03:00"
                    tags: []
                    attachments: []
                example-1:
                  summary: Create Expense Transaction
                  value:
                    id: 2477486740
                    description: Computador
                    date: "2015-09-16"
                    paid: true
                    amount_cents: -100000
                    total_installments: 1
                    installment: 1
                    recurring: false
                    account_id: 6632818
                    category_id: 120321159
                    notes: Pagamento via boleto
                    attachments_count: 0
                    credit_card_id: null
                    credit_card_invoice_id: null
                    paid_credit_card_id: null
                    paid_credit_card_invoice_id: null
                    oposite_transaction_id: null
                    oposite_account_id: null
                    created_at: "2023-04-08T12:41:01-03:00"
                    updated_at: "2023-04-08T12:41:01-03:00"
                    tags: []
                    attachments: []
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Read Transaction
      operationId: readTransaction
      parameters:
        - name: transactionId
          in: path
          schema:
            type: integer
          required: true
          description: ID of the Transaction
          example: "2477489680"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                id: 2477489680
                description: Updated parcelada via API
                date: "2015-12-20"
                paid: true
                amount_cents: 20050
                total_installments: 1
                installment: 1
                recurring: false
                account_id: 6632818
                category_id: 120321159
                notes: Pagamento via boleto
                attachments_count: 0
                credit_card_id: null
                credit_card_invoice_id: null
                paid_credit_card_id: null
                paid_credit_card_invoice_id: null
                oposite_transaction_id: null
                oposite_account_id: null
                created_at: "2023-04-08T12:50:27-03:00"
                updated_at: "2023-04-08T12:52:05-03:00"
                tags: []
                attachments: []
    put:
      tags:
        - Transactions
      summary: Update Transaction
      operationId: updateTransaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                description: Updated parcelada via API
                notes: Pagamento via boleto
                amount_cents: 20050
                date: "2015-12-20"
      parameters:
        - name: transactionId
          in: path
          schema:
            type: integer
          required: true
          description: ID of the Transaction
          example: "101"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
              example:
                id: 2477489680
                description: Updated parcelada via API
                date: "2015-12-20"
                paid: true
                amount_cents: 20050
                total_installments: 1
                installment: 1
                recurring: false
                account_id: 6632818
                category_id: 120321159
                notes: Pagamento via boleto
                attachments_count: 0
                credit_card_id: null
                credit_card_invoice_id: null
                paid_credit_card_id: null
                paid_credit_card_invoice_id: null
                oposite_transaction_id: null
                oposite_account_id: null
                created_at: "2023-04-08T12:50:27-03:00"
                updated_at: "2023-04-08T12:52:05-03:00"
                tags: []
                attachments: []
    delete:
      tags:
        - Transactions
      summary: Delete Transaction
      operationId: deleteTransaction
      parameters:
        - name: transactionId
          in: path
          schema:
            type: integer
          required: true
          description: ID of the Transaction
          example: "101"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                id: 2477483021
                description: Computador
                date: "2015-09-16"
                paid: true
                amount_cents: 0
                total_installments: 1
                installment: 1
                recurring: false
                account_id: 6632818
                category_id: 120321159
                notes: Pagamento via boleto
                attachments_count: 0
                credit_card_id: null
                credit_card_invoice_id: null
                paid_credit_card_id: null
                paid_credit_card_invoice_id: null
                oposite_transaction_id: null
                oposite_account_id: null
                created_at: "2023-04-08T12:30:43-03:00"
                updated_at: "2023-04-08T12:30:43-03:00"
                tags: []
                attachments: []
                deleted: true
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: >-
        The username is your email. The password you can generate at [this
        link](https://app.organizze.com.br/configuracoes/api-keys)
  schemas:
    BankAccount:
      title: Bank Account
      type: object
      additionalProperties: false
      properties:
        id:
          description: ID of the Bank Account
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
        name:
          description: Name of the Bank Account
          type: string
          maxLength: 10000
        institution_id:
          type: string
          maxLength: 10000
        institution_name:
          type: string
          maxLength: 10000
        description:
          type: string
          maxLength: 10000
          nullable: true
        archived:
          type: boolean
        created_at:
          type: string
          pattern: ^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$
          minLength: 20
          maxLength: 29
        updated_at:
          type: string
          pattern: ^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$
          minLength: 20
          maxLength: 29
        default:
          type: boolean
        type:
          type: string
          enum:
            - checking
            - savings
            - other
      example:
        id: 6633003
        name: Nubank Conta Corrente
        institution_id: nuconta
        institution_name: Nubank
        description: null
        archived: false
        created_at: "2023-04-07T13:10:51-03:00"
        updated_at: "2023-04-07T14:11:43-03:00"
        default: false
        type: checking
    Category:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
        name:
          type: string
        color:
          type: string
          minLength: 6
          maxLength: 6
          pattern: ^[a-f0-9]{6}$
        group_id:
          type: string
        fixed:
          type: boolean
        available:
          type: boolean
        essential:
          type: boolean
        parent_id:
          type: integer
          nullable: true
          minimum: 1
          maximum: 2147483647
      example:
        id: 120321144
        name: Bares e restaurantes
        color: "626491"
        group_id: bars_and_restaurants
        fixed: true
        available: true
        essential: false
        parent_id: null
    User:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
        name:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum:
            - sheldon
      example:
        id: 4946248
        name: Rhuan Barreto
        email: test@test.com
        role: sheldon
    CreditCard:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          maximum: 2000000000
        name:
          type: string
        description:
          type: string
          nullable: true
        card_network:
          type: string
        closing_day:
          type: integer
          format: int32
          minimum: 1
          maximum: 31
        due_day:
          type: integer
          format: int32
          minimum: 1
          maximum: 31
        limit_cents:
          type: integer
          format: int32
          minimum: 0
        archived:
          type: boolean
        default:
          type: boolean
        institution_id:
          type: string
        institution_name:
          type: string
          nullable: true
        created_at:
          type: string
          pattern: ^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$
          minLength: 20
          maxLength: 29
        updated_at:
          type: string
          pattern: ^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$
          minLength: 20
          maxLength: 29
        type:
          type: string
          enum:
            - credit_card
      example:
        id: 1287765
        name: Nubank
        description: null
        card_network: default
        closing_day: 8
        due_day: 15
        limit_cents: 1965000
        archived: false
        default: false
        institution_id: default
        institution_name: null
        created_at: "2023-04-07T11:36:48-03:00"
        updated_at: "2023-04-07T13:12:06-03:00"
        type: credit_card
  parameters:
    UserID:
      in: path
      name: userID
      required: true
      description: User ID
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 2147483647
        example: 1
    CategoryID:
      in: path
      name: categoryID
      required: true
      description: Category ID
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 2147483647
        example: 1
    BankAccountID:
      in: path
      name: bankAccountID
      required: true
      description: Bank Account ID
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 2147483647
        example: 1
  responses:
    ListCreditCardsResponse:
      description: List of Credit Cards
      content:
        application/json:
          schema:
            type: array
            minItems: 0
            maxItems: 100
            items:
              $ref: "#/components/schemas/CreditCard"
    ReadCreditCardResponse:
      description: Credit Card
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreditCard"
    ListUsersResponse:
      description: List of Users
      content:
        application/json:
          schema:
            type: array
            minItems: 0
            maxItems: 100
            items:
              $ref: "#/components/schemas/User"
    ReadUserResponse:
      description: User
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/User"
    ListCategoriesResponse:
      description: List of Categories
      content:
        application/json:
          schema:
            type: array
            minItems: 0
            maxItems: 100
            items:
              $ref: "#/components/schemas/Category"
    ReadCategoryResponse:
      description: Category
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Category"
    ListBankAccountsResponse:
      description: List of Bank Accounts
      content:
        application/json:
          schema:
            type: array
            minItems: 0
            maxItems: 100
            items:
              $ref: "#/components/schemas/BankAccount"
    ReadBankAccountResponse:
      description: Bank Account
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BankAccount"
    ItemNotFound:
      description: Item Not Found
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              error:
                type: string
                enum:
                  - registro não encontrado
            example:
              error: registro não encontrado
    Unauthorized:
      description: Authentication issues
      content:
        application/json:
          schema:
            description: Failed Authentication
            type: object
            additionalProperties: false
            properties:
              error:
                type: string
                enum:
                  - Não autorizado
            example:
              error: Não autorizado
        text/html:
          schema:
            description: Missing Authentication
            type: string
            enum: ["HTTP Basic: Access denied."]
            example: "HTTP Basic: Access denied."
